"""create stories table

Revision ID: d15809b18e35
Revises: 228b358ef491
Create Date: 2026-05-29 22:46:27.137183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15809b18e35'
down_revision: Union[str, Sequence[str], None] = '228b358ef491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('number', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('stories_name_key'), 'stories', type_='unique')
    op.drop_column('stories', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('stories_name_key'), 'stories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('stories', 'number')
    # ### end Alembic commands ###
